- hosts: webserver
  remote_user: cloud-user
  sudo: yes
  tasks:
    - name: upload yum repo file to image
      copy: src=local.repo dest=/etc/yum.repos.d/
    - name: ensure apache is at the latest version
      yum: name=httpd state=latest
    - name: make sure apache is running
      service: name=httpd state=running
